spring.application.name=internship

spring.datasource.url=jdbc:postgresql://localhost:5432/intern
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update